// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.axr.interaction_foundation

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object InteractionFeedbackApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class NativeFeedbackCue(val raw: Int) {
  NONE(0),
  TAP(1),
  CONFIRM(2),
  LONG_PRESS(3),
  HOLD_START(4),
  HOLD_WARNING(5),
  HOLD_COMMIT(6),
  SELECT(7),
  DESELECT(8),
  INVALID(9),
  DETENT(10);

  companion object {
    fun ofRaw(raw: Int): NativeFeedbackCue? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeInteractionAudioContext(val raw: Int) {
  INTERACTIVE(0),
  VOICE_CAPTURE(1),
  VOICE_PLAYBACK(2),
  BACKGROUND(3);

  companion object {
    fun ofRaw(raw: Int): NativeInteractionAudioContext? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeSoundRegistration (
  val id: String,
  val packageAssetPath: String,
  val volume: Double,
  val rate: Double,
  val pan: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSoundRegistration {
      val id = pigeonVar_list[0] as String
      val packageAssetPath = pigeonVar_list[1] as String
      val volume = pigeonVar_list[2] as Double
      val rate = pigeonVar_list[3] as Double
      val pan = pigeonVar_list[4] as Double
      return NativeSoundRegistration(id, packageAssetPath, volume, rate, pan)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      packageAssetPath,
      volume,
      rate,
      pan,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSoundRegistration
    return InteractionFeedbackApiPigeonUtils.deepEquals(this.id, other.id) && InteractionFeedbackApiPigeonUtils.deepEquals(this.packageAssetPath, other.packageAssetPath) && InteractionFeedbackApiPigeonUtils.deepEquals(this.volume, other.volume) && InteractionFeedbackApiPigeonUtils.deepEquals(this.rate, other.rate) && InteractionFeedbackApiPigeonUtils.deepEquals(this.pan, other.pan)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.id)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.packageAssetPath)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.volume)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.rate)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.pan)
    return result
  }
  override fun toString(): String {
    return "NativeSoundRegistration(id=$id, packageAssetPath=$packageAssetPath, volume=$volume, rate=$rate, pan=$pan)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeFeedbackConfiguration (
  val contractVersion: Long,
  val soundCoalescingWindowMs: Long,
  val playerPoolSize: Long,
  val respectSilentMode: Boolean,
  val mixWithOthers: Boolean,
  val sounds: List<NativeSoundRegistration>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeFeedbackConfiguration {
      val contractVersion = pigeonVar_list[0] as Long
      val soundCoalescingWindowMs = pigeonVar_list[1] as Long
      val playerPoolSize = pigeonVar_list[2] as Long
      val respectSilentMode = pigeonVar_list[3] as Boolean
      val mixWithOthers = pigeonVar_list[4] as Boolean
      val sounds = pigeonVar_list[5] as List<NativeSoundRegistration>
      return NativeFeedbackConfiguration(contractVersion, soundCoalescingWindowMs, playerPoolSize, respectSilentMode, mixWithOthers, sounds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      soundCoalescingWindowMs,
      playerPoolSize,
      respectSilentMode,
      mixWithOthers,
      sounds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeFeedbackConfiguration
    return InteractionFeedbackApiPigeonUtils.deepEquals(this.contractVersion, other.contractVersion) && InteractionFeedbackApiPigeonUtils.deepEquals(this.soundCoalescingWindowMs, other.soundCoalescingWindowMs) && InteractionFeedbackApiPigeonUtils.deepEquals(this.playerPoolSize, other.playerPoolSize) && InteractionFeedbackApiPigeonUtils.deepEquals(this.respectSilentMode, other.respectSilentMode) && InteractionFeedbackApiPigeonUtils.deepEquals(this.mixWithOthers, other.mixWithOthers) && InteractionFeedbackApiPigeonUtils.deepEquals(this.sounds, other.sounds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.contractVersion)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.soundCoalescingWindowMs)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.playerPoolSize)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.respectSilentMode)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.mixWithOthers)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.sounds)
    return result
  }
  override fun toString(): String {
    return "NativeFeedbackConfiguration(contractVersion=$contractVersion, soundCoalescingWindowMs=$soundCoalescingWindowMs, playerPoolSize=$playerPoolSize, respectSilentMode=$respectSilentMode, mixWithOthers=$mixWithOthers, sounds=$sounds)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeFeedbackRequest (
  val requestId: String,
  val cue: NativeFeedbackCue,
  val soundId: String? = null,
  val soundPriority: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeFeedbackRequest {
      val requestId = pigeonVar_list[0] as String
      val cue = pigeonVar_list[1] as NativeFeedbackCue
      val soundId = pigeonVar_list[2] as String?
      val soundPriority = pigeonVar_list[3] as Long
      return NativeFeedbackRequest(requestId, cue, soundId, soundPriority)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      cue,
      soundId,
      soundPriority,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeFeedbackRequest
    return InteractionFeedbackApiPigeonUtils.deepEquals(this.requestId, other.requestId) && InteractionFeedbackApiPigeonUtils.deepEquals(this.cue, other.cue) && InteractionFeedbackApiPigeonUtils.deepEquals(this.soundId, other.soundId) && InteractionFeedbackApiPigeonUtils.deepEquals(this.soundPriority, other.soundPriority)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.cue)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.soundId)
    result = 31 * result + InteractionFeedbackApiPigeonUtils.deepHash(this.soundPriority)
    return result
  }
  override fun toString(): String {
    return "NativeFeedbackRequest(requestId=$requestId, cue=$cue, soundId=$soundId, soundPriority=$soundPriority)"
  }
}
private open class InteractionFeedbackApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeFeedbackCue.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeInteractionAudioContext.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSoundRegistration.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeFeedbackConfiguration.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeFeedbackRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeFeedbackCue -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeInteractionAudioContext -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NativeSoundRegistration -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeFeedbackConfiguration -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeFeedbackRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeInteractionFeedbackHostApi {
  fun configure(configuration: NativeFeedbackConfiguration)
  fun emit(request: NativeFeedbackRequest)
  fun previewSound(soundId: String)
  fun setAudioContext(context: NativeInteractionAudioContext)
  fun clearPending()

  companion object {
    /** The codec used by NativeInteractionFeedbackHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      InteractionFeedbackApiPigeonCodec()
    }
    /** Sets up an instance of `NativeInteractionFeedbackHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeInteractionFeedbackHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as NativeFeedbackConfiguration
            val wrapped: List<Any?> = try {
              api.configure(configurationArg)
              listOf(null)
            } catch (exception: Throwable) {
              InteractionFeedbackApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.emit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeFeedbackRequest
            val wrapped: List<Any?> = try {
              api.emit(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              InteractionFeedbackApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.previewSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val soundIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.previewSound(soundIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              InteractionFeedbackApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.setAudioContext$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contextArg = args[0] as NativeInteractionAudioContext
            val wrapped: List<Any?> = try {
              api.setAudioContext(contextArg)
              listOf(null)
            } catch (exception: Throwable) {
              InteractionFeedbackApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.clearPending$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearPending()
              listOf(null)
            } catch (exception: Throwable) {
              InteractionFeedbackApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
