// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.axr.interaction_foundation

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object VoiceCaptureApiPigeonUtils {

  fun createConnectionError(channelName: String): VoiceCaptureFlutterError {
    return VoiceCaptureFlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is VoiceCaptureFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class VoiceCaptureFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class VoiceCapturePhaseDto(val raw: Int) {
  IDLE(0),
  REQUESTING_PERMISSIONS(1),
  STARTING(2),
  RECORDING(3),
  FINISHING(4),
  COMPLETED(5),
  FAILED(6),
  INTERRUPTED(7),
  CANCELLED(8);

  companion object {
    fun ofRaw(raw: Int): VoiceCapturePhaseDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VoiceCaptureStatusCodeDto(val raw: Int) {
  READY(0),
  CHECKING_ACCESS(1),
  SPEECH_DENIED(2),
  MICROPHONE_DENIED(3),
  STARTING_MICROPHONE(4),
  RECORDING(5),
  FINISHING_TRANSCRIPTION(6),
  NO_RECORDING(7),
  SPEECH_UNAVAILABLE(8),
  COMPLETED(9),
  NO_RECOGNIZED_TEXT(10),
  MICROPHONE_FAILURE(11),
  INTERRUPTED(12),
  MEDIA_SERVICES_RESET(13),
  CANCELLED(14),
  BUSY(15),
  UNSUPPORTED(16);

  companion object {
    fun ofRaw(raw: Int): VoiceCaptureStatusCodeDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VoicePermissionStateDto(val raw: Int) {
  NOT_DETERMINED(0),
  DENIED(1),
  RESTRICTED(2),
  GRANTED(3),
  UNSUPPORTED(4);

  companion object {
    fun ofRaw(raw: Int): VoicePermissionStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VoiceCaptureCapabilitiesDto (
  val contractVersion: Long,
  val supported: Boolean,
  val speechPermission: VoicePermissionStateDto,
  val microphonePermission: VoicePermissionStateDto,
  val recognizerAvailable: Boolean,
  val unavailableReason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VoiceCaptureCapabilitiesDto {
      val contractVersion = pigeonVar_list[0] as Long
      val supported = pigeonVar_list[1] as Boolean
      val speechPermission = pigeonVar_list[2] as VoicePermissionStateDto
      val microphonePermission = pigeonVar_list[3] as VoicePermissionStateDto
      val recognizerAvailable = pigeonVar_list[4] as Boolean
      val unavailableReason = pigeonVar_list[5] as String?
      return VoiceCaptureCapabilitiesDto(contractVersion, supported, speechPermission, microphonePermission, recognizerAvailable, unavailableReason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      supported,
      speechPermission,
      microphonePermission,
      recognizerAvailable,
      unavailableReason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VoiceCaptureCapabilitiesDto
    return VoiceCaptureApiPigeonUtils.deepEquals(this.contractVersion, other.contractVersion) && VoiceCaptureApiPigeonUtils.deepEquals(this.supported, other.supported) && VoiceCaptureApiPigeonUtils.deepEquals(this.speechPermission, other.speechPermission) && VoiceCaptureApiPigeonUtils.deepEquals(this.microphonePermission, other.microphonePermission) && VoiceCaptureApiPigeonUtils.deepEquals(this.recognizerAvailable, other.recognizerAvailable) && VoiceCaptureApiPigeonUtils.deepEquals(this.unavailableReason, other.unavailableReason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.contractVersion)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.supported)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.speechPermission)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.microphonePermission)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.recognizerAvailable)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.unavailableReason)
    return result
  }
  override fun toString(): String {
    return "VoiceCaptureCapabilitiesDto(contractVersion=$contractVersion, supported=$supported, speechPermission=$speechPermission, microphonePermission=$microphonePermission, recognizerAvailable=$recognizerAvailable, unavailableReason=$unavailableReason)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VoiceCaptureStartRequestDto (
  val contractVersion: Long,
  val operationId: String,
  val mediaId: String,
  val localeIdentifier: String,
  val addsPunctuation: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VoiceCaptureStartRequestDto {
      val contractVersion = pigeonVar_list[0] as Long
      val operationId = pigeonVar_list[1] as String
      val mediaId = pigeonVar_list[2] as String
      val localeIdentifier = pigeonVar_list[3] as String
      val addsPunctuation = pigeonVar_list[4] as Boolean
      return VoiceCaptureStartRequestDto(contractVersion, operationId, mediaId, localeIdentifier, addsPunctuation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      operationId,
      mediaId,
      localeIdentifier,
      addsPunctuation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VoiceCaptureStartRequestDto
    return VoiceCaptureApiPigeonUtils.deepEquals(this.contractVersion, other.contractVersion) && VoiceCaptureApiPigeonUtils.deepEquals(this.operationId, other.operationId) && VoiceCaptureApiPigeonUtils.deepEquals(this.mediaId, other.mediaId) && VoiceCaptureApiPigeonUtils.deepEquals(this.localeIdentifier, other.localeIdentifier) && VoiceCaptureApiPigeonUtils.deepEquals(this.addsPunctuation, other.addsPunctuation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.contractVersion)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.operationId)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.mediaId)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.localeIdentifier)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.addsPunctuation)
    return result
  }
  override fun toString(): String {
    return "VoiceCaptureStartRequestDto(contractVersion=$contractVersion, operationId=$operationId, mediaId=$mediaId, localeIdentifier=$localeIdentifier, addsPunctuation=$addsPunctuation)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VoiceCaptureAckDto (
  val contractVersion: Long,
  val operationId: String,
  val accepted: Boolean,
  val statusCode: VoiceCaptureStatusCodeDto,
  val diagnosticMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VoiceCaptureAckDto {
      val contractVersion = pigeonVar_list[0] as Long
      val operationId = pigeonVar_list[1] as String
      val accepted = pigeonVar_list[2] as Boolean
      val statusCode = pigeonVar_list[3] as VoiceCaptureStatusCodeDto
      val diagnosticMessage = pigeonVar_list[4] as String?
      return VoiceCaptureAckDto(contractVersion, operationId, accepted, statusCode, diagnosticMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      operationId,
      accepted,
      statusCode,
      diagnosticMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VoiceCaptureAckDto
    return VoiceCaptureApiPigeonUtils.deepEquals(this.contractVersion, other.contractVersion) && VoiceCaptureApiPigeonUtils.deepEquals(this.operationId, other.operationId) && VoiceCaptureApiPigeonUtils.deepEquals(this.accepted, other.accepted) && VoiceCaptureApiPigeonUtils.deepEquals(this.statusCode, other.statusCode) && VoiceCaptureApiPigeonUtils.deepEquals(this.diagnosticMessage, other.diagnosticMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.contractVersion)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.operationId)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.accepted)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.statusCode)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.diagnosticMessage)
    return result
  }
  override fun toString(): String {
    return "VoiceCaptureAckDto(contractVersion=$contractVersion, operationId=$operationId, accepted=$accepted, statusCode=$statusCode, diagnosticMessage=$diagnosticMessage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VoiceCaptureResultDto (
  val contractVersion: Long,
  val operationId: String,
  val resultId: String,
  val temporaryFilePath: String,
  val originDeviceId: String,
  val createdAtMicros: Long,
  val durationMs: Long,
  val byteLength: Long,
  val mimeType: String,
  val codec: String,
  val sampleRateHz: Long,
  val channelCount: Long,
  val recognizedText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VoiceCaptureResultDto {
      val contractVersion = pigeonVar_list[0] as Long
      val operationId = pigeonVar_list[1] as String
      val resultId = pigeonVar_list[2] as String
      val temporaryFilePath = pigeonVar_list[3] as String
      val originDeviceId = pigeonVar_list[4] as String
      val createdAtMicros = pigeonVar_list[5] as Long
      val durationMs = pigeonVar_list[6] as Long
      val byteLength = pigeonVar_list[7] as Long
      val mimeType = pigeonVar_list[8] as String
      val codec = pigeonVar_list[9] as String
      val sampleRateHz = pigeonVar_list[10] as Long
      val channelCount = pigeonVar_list[11] as Long
      val recognizedText = pigeonVar_list[12] as String?
      return VoiceCaptureResultDto(contractVersion, operationId, resultId, temporaryFilePath, originDeviceId, createdAtMicros, durationMs, byteLength, mimeType, codec, sampleRateHz, channelCount, recognizedText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      operationId,
      resultId,
      temporaryFilePath,
      originDeviceId,
      createdAtMicros,
      durationMs,
      byteLength,
      mimeType,
      codec,
      sampleRateHz,
      channelCount,
      recognizedText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VoiceCaptureResultDto
    return VoiceCaptureApiPigeonUtils.deepEquals(this.contractVersion, other.contractVersion) && VoiceCaptureApiPigeonUtils.deepEquals(this.operationId, other.operationId) && VoiceCaptureApiPigeonUtils.deepEquals(this.resultId, other.resultId) && VoiceCaptureApiPigeonUtils.deepEquals(this.temporaryFilePath, other.temporaryFilePath) && VoiceCaptureApiPigeonUtils.deepEquals(this.originDeviceId, other.originDeviceId) && VoiceCaptureApiPigeonUtils.deepEquals(this.createdAtMicros, other.createdAtMicros) && VoiceCaptureApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && VoiceCaptureApiPigeonUtils.deepEquals(this.byteLength, other.byteLength) && VoiceCaptureApiPigeonUtils.deepEquals(this.mimeType, other.mimeType) && VoiceCaptureApiPigeonUtils.deepEquals(this.codec, other.codec) && VoiceCaptureApiPigeonUtils.deepEquals(this.sampleRateHz, other.sampleRateHz) && VoiceCaptureApiPigeonUtils.deepEquals(this.channelCount, other.channelCount) && VoiceCaptureApiPigeonUtils.deepEquals(this.recognizedText, other.recognizedText)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.contractVersion)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.operationId)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.resultId)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.temporaryFilePath)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.originDeviceId)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.createdAtMicros)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.byteLength)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.mimeType)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.codec)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.sampleRateHz)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.channelCount)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.recognizedText)
    return result
  }
  override fun toString(): String {
    return "VoiceCaptureResultDto(contractVersion=$contractVersion, operationId=$operationId, resultId=$resultId, temporaryFilePath=$temporaryFilePath, originDeviceId=$originDeviceId, createdAtMicros=$createdAtMicros, durationMs=$durationMs, byteLength=$byteLength, mimeType=$mimeType, codec=$codec, sampleRateHz=$sampleRateHz, channelCount=$channelCount, recognizedText=$recognizedText)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VoiceCaptureEventDto (
  val contractVersion: Long,
  val operationId: String,
  val sequence: Long,
  val phase: VoiceCapturePhaseDto,
  val statusCode: VoiceCaptureStatusCodeDto,
  val diagnosticMessage: String? = null,
  val result: VoiceCaptureResultDto? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VoiceCaptureEventDto {
      val contractVersion = pigeonVar_list[0] as Long
      val operationId = pigeonVar_list[1] as String
      val sequence = pigeonVar_list[2] as Long
      val phase = pigeonVar_list[3] as VoiceCapturePhaseDto
      val statusCode = pigeonVar_list[4] as VoiceCaptureStatusCodeDto
      val diagnosticMessage = pigeonVar_list[5] as String?
      val result = pigeonVar_list[6] as VoiceCaptureResultDto?
      return VoiceCaptureEventDto(contractVersion, operationId, sequence, phase, statusCode, diagnosticMessage, result)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      operationId,
      sequence,
      phase,
      statusCode,
      diagnosticMessage,
      result,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VoiceCaptureEventDto
    return VoiceCaptureApiPigeonUtils.deepEquals(this.contractVersion, other.contractVersion) && VoiceCaptureApiPigeonUtils.deepEquals(this.operationId, other.operationId) && VoiceCaptureApiPigeonUtils.deepEquals(this.sequence, other.sequence) && VoiceCaptureApiPigeonUtils.deepEquals(this.phase, other.phase) && VoiceCaptureApiPigeonUtils.deepEquals(this.statusCode, other.statusCode) && VoiceCaptureApiPigeonUtils.deepEquals(this.diagnosticMessage, other.diagnosticMessage) && VoiceCaptureApiPigeonUtils.deepEquals(this.result, other.result)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.contractVersion)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.operationId)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.sequence)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.phase)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.statusCode)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.diagnosticMessage)
    result = 31 * result + VoiceCaptureApiPigeonUtils.deepHash(this.result)
    return result
  }
  override fun toString(): String {
    return "VoiceCaptureEventDto(contractVersion=$contractVersion, operationId=$operationId, sequence=$sequence, phase=$phase, statusCode=$statusCode, diagnosticMessage=$diagnosticMessage, result=$result)"
  }
}
private open class VoiceCaptureApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VoiceCapturePhaseDto.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VoiceCaptureStatusCodeDto.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VoicePermissionStateDto.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoiceCaptureCapabilitiesDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoiceCaptureStartRequestDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoiceCaptureAckDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoiceCaptureResultDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoiceCaptureEventDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VoiceCapturePhaseDto -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VoiceCaptureStatusCodeDto -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is VoicePermissionStateDto -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is VoiceCaptureCapabilitiesDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is VoiceCaptureStartRequestDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is VoiceCaptureAckDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is VoiceCaptureResultDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is VoiceCaptureEventDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VoiceCaptureHostApi {
  fun getCapabilities(localeIdentifier: String, callback: (Result<VoiceCaptureCapabilitiesDto>) -> Unit)
  fun startCapture(request: VoiceCaptureStartRequestDto, callback: (Result<VoiceCaptureAckDto>) -> Unit)
  fun stopCapture(operationId: String, callback: (Result<VoiceCaptureAckDto>) -> Unit)
  fun cancelCapture(operationId: String, callback: (Result<VoiceCaptureAckDto>) -> Unit)
  fun releaseResult(resultId: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by VoiceCaptureHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      VoiceCaptureApiPigeonCodec()
    }
    /** Sets up an instance of `VoiceCaptureHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VoiceCaptureHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.getCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val localeIdentifierArg = args[0] as String
            api.getCapabilities(localeIdentifierArg) { result: Result<VoiceCaptureCapabilitiesDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VoiceCaptureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VoiceCaptureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.startCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VoiceCaptureStartRequestDto
            api.startCapture(requestArg) { result: Result<VoiceCaptureAckDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VoiceCaptureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VoiceCaptureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.stopCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val operationIdArg = args[0] as String
            api.stopCapture(operationIdArg) { result: Result<VoiceCaptureAckDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VoiceCaptureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VoiceCaptureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.cancelCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val operationIdArg = args[0] as String
            api.cancelCapture(operationIdArg) { result: Result<VoiceCaptureAckDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VoiceCaptureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VoiceCaptureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.releaseResult$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val resultIdArg = args[0] as String
            api.releaseResult(resultIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VoiceCaptureApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(VoiceCaptureApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VoiceCaptureFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VoiceCaptureFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      VoiceCaptureApiPigeonCodec()
    }
  }
  fun onCaptureEvent(eventArg: VoiceCaptureEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.interaction_foundation.VoiceCaptureFlutterApi.onCaptureEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(VoiceCaptureFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VoiceCaptureApiPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
