// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.alex.margaritaville.flutter.beta.edr

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object EdrOverlayApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class EdrPresentationOutcome(val raw: Int) {
  TRANSPARENT_PRESENTED(0),
  STRUCTURALLY_DETACHED(1),
  NEVER_PRESENTED_FLUTTER_ONLY(2),
  STALE_REJECTED(3),
  FAILED(4);

  companion object {
    fun ofRaw(raw: Int): EdrPresentationOutcome? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EdrTileSnapshot (
  val roomId: String,
  val timeText: String,
  val left: Double,
  val top: Double,
  val width: Double,
  val height: Double,
  val cornerRadius: Double,
  val baseColorArgb: Long,
  val vipHdrEnabled: Boolean,
  val vipJellyEnabled: Boolean,
  val vipJellySpeed: Double,
  val pulseGeneration: Long? = null,
  val pulseColorArgb: Long? = null,
  val pulseBoostColorArgb: Long? = null,
  val pulseStartedAtMicros: Long? = null,
  val springIntensity: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EdrTileSnapshot {
      val roomId = pigeonVar_list[0] as String
      val timeText = pigeonVar_list[1] as String
      val left = pigeonVar_list[2] as Double
      val top = pigeonVar_list[3] as Double
      val width = pigeonVar_list[4] as Double
      val height = pigeonVar_list[5] as Double
      val cornerRadius = pigeonVar_list[6] as Double
      val baseColorArgb = pigeonVar_list[7] as Long
      val vipHdrEnabled = pigeonVar_list[8] as Boolean
      val vipJellyEnabled = pigeonVar_list[9] as Boolean
      val vipJellySpeed = pigeonVar_list[10] as Double
      val pulseGeneration = pigeonVar_list[11] as Long?
      val pulseColorArgb = pigeonVar_list[12] as Long?
      val pulseBoostColorArgb = pigeonVar_list[13] as Long?
      val pulseStartedAtMicros = pigeonVar_list[14] as Long?
      val springIntensity = pigeonVar_list[15] as Double
      return EdrTileSnapshot(roomId, timeText, left, top, width, height, cornerRadius, baseColorArgb, vipHdrEnabled, vipJellyEnabled, vipJellySpeed, pulseGeneration, pulseColorArgb, pulseBoostColorArgb, pulseStartedAtMicros, springIntensity)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      roomId,
      timeText,
      left,
      top,
      width,
      height,
      cornerRadius,
      baseColorArgb,
      vipHdrEnabled,
      vipJellyEnabled,
      vipJellySpeed,
      pulseGeneration,
      pulseColorArgb,
      pulseBoostColorArgb,
      pulseStartedAtMicros,
      springIntensity,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EdrTileSnapshot
    return EdrOverlayApiPigeonUtils.deepEquals(this.roomId, other.roomId) && EdrOverlayApiPigeonUtils.deepEquals(this.timeText, other.timeText) && EdrOverlayApiPigeonUtils.deepEquals(this.left, other.left) && EdrOverlayApiPigeonUtils.deepEquals(this.top, other.top) && EdrOverlayApiPigeonUtils.deepEquals(this.width, other.width) && EdrOverlayApiPigeonUtils.deepEquals(this.height, other.height) && EdrOverlayApiPigeonUtils.deepEquals(this.cornerRadius, other.cornerRadius) && EdrOverlayApiPigeonUtils.deepEquals(this.baseColorArgb, other.baseColorArgb) && EdrOverlayApiPigeonUtils.deepEquals(this.vipHdrEnabled, other.vipHdrEnabled) && EdrOverlayApiPigeonUtils.deepEquals(this.vipJellyEnabled, other.vipJellyEnabled) && EdrOverlayApiPigeonUtils.deepEquals(this.vipJellySpeed, other.vipJellySpeed) && EdrOverlayApiPigeonUtils.deepEquals(this.pulseGeneration, other.pulseGeneration) && EdrOverlayApiPigeonUtils.deepEquals(this.pulseColorArgb, other.pulseColorArgb) && EdrOverlayApiPigeonUtils.deepEquals(this.pulseBoostColorArgb, other.pulseBoostColorArgb) && EdrOverlayApiPigeonUtils.deepEquals(this.pulseStartedAtMicros, other.pulseStartedAtMicros) && EdrOverlayApiPigeonUtils.deepEquals(this.springIntensity, other.springIntensity)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.roomId)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.timeText)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.left)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.top)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.width)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.height)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.cornerRadius)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.baseColorArgb)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.vipHdrEnabled)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.vipJellyEnabled)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.vipJellySpeed)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.pulseGeneration)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.pulseColorArgb)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.pulseBoostColorArgb)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.pulseStartedAtMicros)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.springIntensity)
    return result
  }
  override fun toString(): String {
    return "EdrTileSnapshot(roomId=$roomId, timeText=$timeText, left=$left, top=$top, width=$width, height=$height, cornerRadius=$cornerRadius, baseColorArgb=$baseColorArgb, vipHdrEnabled=$vipHdrEnabled, vipJellyEnabled=$vipJellyEnabled, vipJellySpeed=$vipJellySpeed, pulseGeneration=$pulseGeneration, pulseColorArgb=$pulseColorArgb, pulseBoostColorArgb=$pulseBoostColorArgb, pulseStartedAtMicros=$pulseStartedAtMicros, springIntensity=$springIntensity)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EdrPresentationAck (
  val surfaceSessionId: Long,
  val activationId: Long,
  val presentationRevision: Long,
  val suppressed: Boolean,
  val outcome: EdrPresentationOutcome,
  val nativeGeneration: Long,
  val presentedAtNanos: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EdrPresentationAck {
      val surfaceSessionId = pigeonVar_list[0] as Long
      val activationId = pigeonVar_list[1] as Long
      val presentationRevision = pigeonVar_list[2] as Long
      val suppressed = pigeonVar_list[3] as Boolean
      val outcome = pigeonVar_list[4] as EdrPresentationOutcome
      val nativeGeneration = pigeonVar_list[5] as Long
      val presentedAtNanos = pigeonVar_list[6] as Long
      return EdrPresentationAck(surfaceSessionId, activationId, presentationRevision, suppressed, outcome, nativeGeneration, presentedAtNanos)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      surfaceSessionId,
      activationId,
      presentationRevision,
      suppressed,
      outcome,
      nativeGeneration,
      presentedAtNanos,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EdrPresentationAck
    return EdrOverlayApiPigeonUtils.deepEquals(this.surfaceSessionId, other.surfaceSessionId) && EdrOverlayApiPigeonUtils.deepEquals(this.activationId, other.activationId) && EdrOverlayApiPigeonUtils.deepEquals(this.presentationRevision, other.presentationRevision) && EdrOverlayApiPigeonUtils.deepEquals(this.suppressed, other.suppressed) && EdrOverlayApiPigeonUtils.deepEquals(this.outcome, other.outcome) && EdrOverlayApiPigeonUtils.deepEquals(this.nativeGeneration, other.nativeGeneration) && EdrOverlayApiPigeonUtils.deepEquals(this.presentedAtNanos, other.presentedAtNanos)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.surfaceSessionId)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.activationId)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.presentationRevision)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.suppressed)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.outcome)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.nativeGeneration)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.presentedAtNanos)
    return result
  }
  override fun toString(): String {
    return "EdrPresentationAck(surfaceSessionId=$surfaceSessionId, activationId=$activationId, presentationRevision=$presentationRevision, suppressed=$suppressed, outcome=$outcome, nativeGeneration=$nativeGeneration, presentedAtNanos=$presentedAtNanos)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EdrReadyAck (
  val surfaceSessionId: Long,
  val activationId: Long,
  val contentRevision: Long,
  val presentationRevision: Long,
  val accepted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EdrReadyAck {
      val surfaceSessionId = pigeonVar_list[0] as Long
      val activationId = pigeonVar_list[1] as Long
      val contentRevision = pigeonVar_list[2] as Long
      val presentationRevision = pigeonVar_list[3] as Long
      val accepted = pigeonVar_list[4] as Boolean
      return EdrReadyAck(surfaceSessionId, activationId, contentRevision, presentationRevision, accepted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      surfaceSessionId,
      activationId,
      contentRevision,
      presentationRevision,
      accepted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EdrReadyAck
    return EdrOverlayApiPigeonUtils.deepEquals(this.surfaceSessionId, other.surfaceSessionId) && EdrOverlayApiPigeonUtils.deepEquals(this.activationId, other.activationId) && EdrOverlayApiPigeonUtils.deepEquals(this.contentRevision, other.contentRevision) && EdrOverlayApiPigeonUtils.deepEquals(this.presentationRevision, other.presentationRevision) && EdrOverlayApiPigeonUtils.deepEquals(this.accepted, other.accepted)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.surfaceSessionId)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.activationId)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.contentRevision)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.presentationRevision)
    result = 31 * result + EdrOverlayApiPigeonUtils.deepHash(this.accepted)
    return result
  }
  override fun toString(): String {
    return "EdrReadyAck(surfaceSessionId=$surfaceSessionId, activationId=$activationId, contentRevision=$contentRevision, presentationRevision=$presentationRevision, accepted=$accepted)"
  }
}
private open class EdrOverlayApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EdrPresentationOutcome.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EdrTileSnapshot.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EdrPresentationAck.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EdrReadyAck.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EdrPresentationOutcome -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is EdrTileSnapshot -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is EdrPresentationAck -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is EdrReadyAck -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface EdrOverlayHostApi {
  fun configureWindow(surfaceSessionId: Long, activationId: Long, layoutGeneration: Long, contentRevision: Long, presentationRevision: Long, geometryRevision: Long, viewportLeft: Double, viewportTop: Double, viewportWidth: Double, viewportHeight: Double, scrollOffsetX: Double, scrollOffsetY: Double, tiles: List<EdrTileSnapshot>)
  fun updateWindowGeometry(surfaceSessionId: Long, activationId: Long, layoutGeneration: Long, presentationRevision: Long, geometryRevision: Long, viewportLeft: Double, viewportTop: Double, viewportWidth: Double, viewportHeight: Double, scrollOffsetX: Double, scrollOffsetY: Double)
  fun suspendWindow(surfaceSessionId: Long, activationId: Long, presentationRevision: Long, callback: (Result<EdrPresentationAck>) -> Unit)
  fun clearWindow(surfaceSessionId: Long, activationId: Long, contentRevision: Long)

  companion object {
    /** The codec used by EdrOverlayHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      EdrOverlayApiPigeonCodec()
    }
    /** Sets up an instance of `EdrOverlayHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EdrOverlayHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.margaritaville_flutter.EdrOverlayHostApi.configureWindow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val surfaceSessionIdArg = args[0] as Long
            val activationIdArg = args[1] as Long
            val layoutGenerationArg = args[2] as Long
            val contentRevisionArg = args[3] as Long
            val presentationRevisionArg = args[4] as Long
            val geometryRevisionArg = args[5] as Long
            val viewportLeftArg = args[6] as Double
            val viewportTopArg = args[7] as Double
            val viewportWidthArg = args[8] as Double
            val viewportHeightArg = args[9] as Double
            val scrollOffsetXArg = args[10] as Double
            val scrollOffsetYArg = args[11] as Double
            val tilesArg = args[12] as List<EdrTileSnapshot>
            val wrapped: List<Any?> = try {
              api.configureWindow(surfaceSessionIdArg, activationIdArg, layoutGenerationArg, contentRevisionArg, presentationRevisionArg, geometryRevisionArg, viewportLeftArg, viewportTopArg, viewportWidthArg, viewportHeightArg, scrollOffsetXArg, scrollOffsetYArg, tilesArg)
              listOf(null)
            } catch (exception: Throwable) {
              EdrOverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.margaritaville_flutter.EdrOverlayHostApi.updateWindowGeometry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val surfaceSessionIdArg = args[0] as Long
            val activationIdArg = args[1] as Long
            val layoutGenerationArg = args[2] as Long
            val presentationRevisionArg = args[3] as Long
            val geometryRevisionArg = args[4] as Long
            val viewportLeftArg = args[5] as Double
            val viewportTopArg = args[6] as Double
            val viewportWidthArg = args[7] as Double
            val viewportHeightArg = args[8] as Double
            val scrollOffsetXArg = args[9] as Double
            val scrollOffsetYArg = args[10] as Double
            val wrapped: List<Any?> = try {
              api.updateWindowGeometry(surfaceSessionIdArg, activationIdArg, layoutGenerationArg, presentationRevisionArg, geometryRevisionArg, viewportLeftArg, viewportTopArg, viewportWidthArg, viewportHeightArg, scrollOffsetXArg, scrollOffsetYArg)
              listOf(null)
            } catch (exception: Throwable) {
              EdrOverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.margaritaville_flutter.EdrOverlayHostApi.suspendWindow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val surfaceSessionIdArg = args[0] as Long
            val activationIdArg = args[1] as Long
            val presentationRevisionArg = args[2] as Long
            api.suspendWindow(surfaceSessionIdArg, activationIdArg, presentationRevisionArg) { result: Result<EdrPresentationAck> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EdrOverlayApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EdrOverlayApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.margaritaville_flutter.EdrOverlayHostApi.clearWindow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val surfaceSessionIdArg = args[0] as Long
            val activationIdArg = args[1] as Long
            val contentRevisionArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.clearWindow(surfaceSessionIdArg, activationIdArg, contentRevisionArg)
              listOf(null)
            } catch (exception: Throwable) {
              EdrOverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class EdrOverlayFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EdrOverlayFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      EdrOverlayApiPigeonCodec()
    }
  }
  fun windowReady(surfaceSessionIdArg: Long, activationIdArg: Long, contentRevisionArg: Long, presentationRevisionArg: Long, callback: (Result<EdrReadyAck>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.margaritaville_flutter.EdrOverlayFlutterApi.windowReady$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(surfaceSessionIdArg, activationIdArg, contentRevisionArg, presentationRevisionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as EdrReadyAck
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(EdrOverlayApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
