// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum EdrOverlayApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct EdrTileSnapshot: Hashable, CustomStringConvertible {
  var roomId: String
  var left: Double
  var top: Double
  var width: Double
  var height: Double
  var cornerRadius: Double
  var baseColorArgb: Int64
  var vipHdrEnabled: Bool
  var vipJellyEnabled: Bool
  var vipJellySpeed: Double
  var pulseGeneration: Int64? = nil
  var pulseColorArgb: Int64? = nil
  var pulseStartedAtMicros: Int64? = nil
  var springIntensity: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EdrTileSnapshot? {
    let roomId = pigeonVar_list[0] as! String
    let left = pigeonVar_list[1] as! Double
    let top = pigeonVar_list[2] as! Double
    let width = pigeonVar_list[3] as! Double
    let height = pigeonVar_list[4] as! Double
    let cornerRadius = pigeonVar_list[5] as! Double
    let baseColorArgb = pigeonVar_list[6] as! Int64
    let vipHdrEnabled = pigeonVar_list[7] as! Bool
    let vipJellyEnabled = pigeonVar_list[8] as! Bool
    let vipJellySpeed = pigeonVar_list[9] as! Double
    let pulseGeneration: Int64? = nilOrValue(pigeonVar_list[10])
    let pulseColorArgb: Int64? = nilOrValue(pigeonVar_list[11])
    let pulseStartedAtMicros: Int64? = nilOrValue(pigeonVar_list[12])
    let springIntensity = pigeonVar_list[13] as! Double

    return EdrTileSnapshot(
      roomId: roomId,
      left: left,
      top: top,
      width: width,
      height: height,
      cornerRadius: cornerRadius,
      baseColorArgb: baseColorArgb,
      vipHdrEnabled: vipHdrEnabled,
      vipJellyEnabled: vipJellyEnabled,
      vipJellySpeed: vipJellySpeed,
      pulseGeneration: pulseGeneration,
      pulseColorArgb: pulseColorArgb,
      pulseStartedAtMicros: pulseStartedAtMicros,
      springIntensity: springIntensity
    )
  }
  func toList() -> [Any?] {
    return [
      roomId,
      left,
      top,
      width,
      height,
      cornerRadius,
      baseColorArgb,
      vipHdrEnabled,
      vipJellyEnabled,
      vipJellySpeed,
      pulseGeneration,
      pulseColorArgb,
      pulseStartedAtMicros,
      springIntensity,
    ]
  }
  static func == (lhs: EdrTileSnapshot, rhs: EdrTileSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return EdrOverlayApiPigeonInternal.deepEquals(lhs.roomId, rhs.roomId) && EdrOverlayApiPigeonInternal.deepEquals(lhs.left, rhs.left) && EdrOverlayApiPigeonInternal.deepEquals(lhs.top, rhs.top) && EdrOverlayApiPigeonInternal.deepEquals(lhs.width, rhs.width) && EdrOverlayApiPigeonInternal.deepEquals(lhs.height, rhs.height) && EdrOverlayApiPigeonInternal.deepEquals(lhs.cornerRadius, rhs.cornerRadius) && EdrOverlayApiPigeonInternal.deepEquals(lhs.baseColorArgb, rhs.baseColorArgb) && EdrOverlayApiPigeonInternal.deepEquals(lhs.vipHdrEnabled, rhs.vipHdrEnabled) && EdrOverlayApiPigeonInternal.deepEquals(lhs.vipJellyEnabled, rhs.vipJellyEnabled) && EdrOverlayApiPigeonInternal.deepEquals(lhs.vipJellySpeed, rhs.vipJellySpeed) && EdrOverlayApiPigeonInternal.deepEquals(lhs.pulseGeneration, rhs.pulseGeneration) && EdrOverlayApiPigeonInternal.deepEquals(lhs.pulseColorArgb, rhs.pulseColorArgb) && EdrOverlayApiPigeonInternal.deepEquals(lhs.pulseStartedAtMicros, rhs.pulseStartedAtMicros) && EdrOverlayApiPigeonInternal.deepEquals(lhs.springIntensity, rhs.springIntensity)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EdrTileSnapshot")
    EdrOverlayApiPigeonInternal.deepHash(value: roomId, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: left, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: top, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: cornerRadius, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: baseColorArgb, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: vipHdrEnabled, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: vipJellyEnabled, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: vipJellySpeed, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: pulseGeneration, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: pulseColorArgb, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: pulseStartedAtMicros, hasher: &hasher)
    EdrOverlayApiPigeonInternal.deepHash(value: springIntensity, hasher: &hasher)
  }

  public var description: String {
    return "EdrTileSnapshot(roomId: \(String(describing: roomId)), left: \(String(describing: left)), top: \(String(describing: top)), width: \(String(describing: width)), height: \(String(describing: height)), cornerRadius: \(String(describing: cornerRadius)), baseColorArgb: \(String(describing: baseColorArgb)), vipHdrEnabled: \(String(describing: vipHdrEnabled)), vipJellyEnabled: \(String(describing: vipJellyEnabled)), vipJellySpeed: \(String(describing: vipJellySpeed)), pulseGeneration: \(String(describing: pulseGeneration)), pulseColorArgb: \(String(describing: pulseColorArgb)), pulseStartedAtMicros: \(String(describing: pulseStartedAtMicros)), springIntensity: \(String(describing: springIntensity)))"
  }
}

private class EdrOverlayApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return EdrTileSnapshot.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class EdrOverlayApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? EdrTileSnapshot {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class EdrOverlayApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return EdrOverlayApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return EdrOverlayApiPigeonCodecWriter(data: data)
  }
}

class EdrOverlayApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = EdrOverlayApiPigeonCodec(readerWriter: EdrOverlayApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EdrOverlayHostApi {
  func updateTiles(viewId: Int64, tiles: [EdrTileSnapshot]) throws
  func clearTiles(viewId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EdrOverlayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { EdrOverlayApiPigeonCodec.shared }
  /// Sets up an instance of `EdrOverlayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EdrOverlayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let updateTilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.margaritaville_flutter.EdrOverlayHostApi.updateTiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateTilesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let tilesArg = args[1] as! [EdrTileSnapshot]
        do {
          try api.updateTiles(viewId: viewIdArg, tiles: tilesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateTilesChannel.setMessageHandler(nil)
    }
    let clearTilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.margaritaville_flutter.EdrOverlayHostApi.clearTiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearTilesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          try api.clearTiles(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearTilesChannel.setMessageHandler(nil)
    }
  }
}
