// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum InteractionFeedbackApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum NativeFeedbackCue: Int, CaseIterable {
  case none = 0
  case tap = 1
  case confirm = 2
  case longPress = 3
  case holdStart = 4
  case holdWarning = 5
  case holdCommit = 6
  case select = 7
  case deselect = 8
  case invalid = 9
  case detent = 10
}

enum NativeInteractionAudioContext: Int, CaseIterable {
  case interactive = 0
  case voiceCapture = 1
  case voicePlayback = 2
  case background = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeSoundRegistration: Hashable, CustomStringConvertible {
  var id: String
  var packageAssetPath: String
  var volume: Double
  var rate: Double
  var pan: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSoundRegistration? {
    let id = pigeonVar_list[0] as! String
    let packageAssetPath = pigeonVar_list[1] as! String
    let volume = pigeonVar_list[2] as! Double
    let rate = pigeonVar_list[3] as! Double
    let pan = pigeonVar_list[4] as! Double

    return NativeSoundRegistration(
      id: id,
      packageAssetPath: packageAssetPath,
      volume: volume,
      rate: rate,
      pan: pan
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      packageAssetPath,
      volume,
      rate,
      pan,
    ]
  }
  static func == (lhs: NativeSoundRegistration, rhs: NativeSoundRegistration) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return InteractionFeedbackApiPigeonInternal.deepEquals(lhs.id, rhs.id) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.packageAssetPath, rhs.packageAssetPath) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.volume, rhs.volume) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.rate, rhs.rate) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.pan, rhs.pan)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSoundRegistration")
    InteractionFeedbackApiPigeonInternal.deepHash(value: id, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: packageAssetPath, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: volume, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: rate, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: pan, hasher: &hasher)
  }

  public var description: String {
    return "NativeSoundRegistration(id: \(String(describing: id)), packageAssetPath: \(String(describing: packageAssetPath)), volume: \(String(describing: volume)), rate: \(String(describing: rate)), pan: \(String(describing: pan)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeFeedbackConfiguration: Hashable, CustomStringConvertible {
  var contractVersion: Int64
  var soundCoalescingWindowMs: Int64
  var playerPoolSize: Int64
  var respectSilentMode: Bool
  var mixWithOthers: Bool
  var sounds: [NativeSoundRegistration]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeFeedbackConfiguration? {
    let contractVersion = pigeonVar_list[0] as! Int64
    let soundCoalescingWindowMs = pigeonVar_list[1] as! Int64
    let playerPoolSize = pigeonVar_list[2] as! Int64
    let respectSilentMode = pigeonVar_list[3] as! Bool
    let mixWithOthers = pigeonVar_list[4] as! Bool
    let sounds = pigeonVar_list[5] as! [NativeSoundRegistration]

    return NativeFeedbackConfiguration(
      contractVersion: contractVersion,
      soundCoalescingWindowMs: soundCoalescingWindowMs,
      playerPoolSize: playerPoolSize,
      respectSilentMode: respectSilentMode,
      mixWithOthers: mixWithOthers,
      sounds: sounds
    )
  }
  func toList() -> [Any?] {
    return [
      contractVersion,
      soundCoalescingWindowMs,
      playerPoolSize,
      respectSilentMode,
      mixWithOthers,
      sounds,
    ]
  }
  static func == (lhs: NativeFeedbackConfiguration, rhs: NativeFeedbackConfiguration) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return InteractionFeedbackApiPigeonInternal.deepEquals(lhs.contractVersion, rhs.contractVersion) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.soundCoalescingWindowMs, rhs.soundCoalescingWindowMs) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.playerPoolSize, rhs.playerPoolSize) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.respectSilentMode, rhs.respectSilentMode) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.mixWithOthers, rhs.mixWithOthers) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.sounds, rhs.sounds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeFeedbackConfiguration")
    InteractionFeedbackApiPigeonInternal.deepHash(value: contractVersion, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: soundCoalescingWindowMs, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: playerPoolSize, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: respectSilentMode, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: mixWithOthers, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: sounds, hasher: &hasher)
  }

  public var description: String {
    return "NativeFeedbackConfiguration(contractVersion: \(String(describing: contractVersion)), soundCoalescingWindowMs: \(String(describing: soundCoalescingWindowMs)), playerPoolSize: \(String(describing: playerPoolSize)), respectSilentMode: \(String(describing: respectSilentMode)), mixWithOthers: \(String(describing: mixWithOthers)), sounds: \(String(describing: sounds)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeFeedbackRequest: Hashable, CustomStringConvertible {
  var requestId: String
  var cue: NativeFeedbackCue
  var soundId: String? = nil
  var soundPriority: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeFeedbackRequest? {
    let requestId = pigeonVar_list[0] as! String
    let cue = pigeonVar_list[1] as! NativeFeedbackCue
    let soundId: String? = nilOrValue(pigeonVar_list[2])
    let soundPriority = pigeonVar_list[3] as! Int64

    return NativeFeedbackRequest(
      requestId: requestId,
      cue: cue,
      soundId: soundId,
      soundPriority: soundPriority
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      cue,
      soundId,
      soundPriority,
    ]
  }
  static func == (lhs: NativeFeedbackRequest, rhs: NativeFeedbackRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return InteractionFeedbackApiPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.cue, rhs.cue) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.soundId, rhs.soundId) && InteractionFeedbackApiPigeonInternal.deepEquals(lhs.soundPriority, rhs.soundPriority)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeFeedbackRequest")
    InteractionFeedbackApiPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: cue, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: soundId, hasher: &hasher)
    InteractionFeedbackApiPigeonInternal.deepHash(value: soundPriority, hasher: &hasher)
  }

  public var description: String {
    return "NativeFeedbackRequest(requestId: \(String(describing: requestId)), cue: \(String(describing: cue)), soundId: \(String(describing: soundId)), soundPriority: \(String(describing: soundPriority)))"
  }
}

private class InteractionFeedbackApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeFeedbackCue(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeInteractionAudioContext(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return NativeSoundRegistration.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeFeedbackConfiguration.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeFeedbackRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class InteractionFeedbackApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeFeedbackCue {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeInteractionAudioContext {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeSoundRegistration {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeFeedbackConfiguration {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeFeedbackRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class InteractionFeedbackApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return InteractionFeedbackApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return InteractionFeedbackApiPigeonCodecWriter(data: data)
  }
}

class InteractionFeedbackApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = InteractionFeedbackApiPigeonCodec(readerWriter: InteractionFeedbackApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeInteractionFeedbackHostApi {
  func configure(configuration: NativeFeedbackConfiguration) throws
  func emit(request: NativeFeedbackRequest) throws
  func previewSound(soundId: String) throws
  func setAudioContext(context: NativeInteractionAudioContext) throws
  func clearPending() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeInteractionFeedbackHostApiSetup {
  static var codec: FlutterStandardMessageCodec { InteractionFeedbackApiPigeonCodec.shared }
  /// Sets up an instance of `NativeInteractionFeedbackHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeInteractionFeedbackHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! NativeFeedbackConfiguration
        do {
          try api.configure(configuration: configurationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let emitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.emit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      emitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeFeedbackRequest
        do {
          try api.emit(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      emitChannel.setMessageHandler(nil)
    }
    let previewSoundChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.previewSound\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      previewSoundChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let soundIdArg = args[0] as! String
        do {
          try api.previewSound(soundId: soundIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      previewSoundChannel.setMessageHandler(nil)
    }
    let setAudioContextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.setAudioContext\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAudioContextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let contextArg = args[0] as! NativeInteractionAudioContext
        do {
          try api.setAudioContext(context: contextArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAudioContextChannel.setMessageHandler(nil)
    }
    let clearPendingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.NativeInteractionFeedbackHostApi.clearPending\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearPendingChannel.setMessageHandler { _, reply in
        do {
          try api.clearPending()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearPendingChannel.setMessageHandler(nil)
    }
  }
}
