// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class VoiceCapturePigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "VoiceCapturePigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? VoiceCapturePigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> VoiceCapturePigeonError {
  return VoiceCapturePigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum VoiceCaptureApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum VoiceCapturePhaseDto: Int, CaseIterable {
  case idle = 0
  case requestingPermissions = 1
  case starting = 2
  case recording = 3
  case finishing = 4
  case completed = 5
  case failed = 6
  case interrupted = 7
  case cancelled = 8
}

enum VoiceCaptureStatusCodeDto: Int, CaseIterable {
  case ready = 0
  case checkingAccess = 1
  case speechDenied = 2
  case microphoneDenied = 3
  case startingMicrophone = 4
  case recording = 5
  case finishingTranscription = 6
  case noRecording = 7
  case speechUnavailable = 8
  case completed = 9
  case noRecognizedText = 10
  case microphoneFailure = 11
  case interrupted = 12
  case mediaServicesReset = 13
  case cancelled = 14
  case busy = 15
  case unsupported = 16
}

enum VoicePermissionStateDto: Int, CaseIterable {
  case notDetermined = 0
  case denied = 1
  case restricted = 2
  case granted = 3
  case unsupported = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct VoiceCaptureCapabilitiesDto: Hashable, CustomStringConvertible {
  var contractVersion: Int64
  var supported: Bool
  var speechPermission: VoicePermissionStateDto
  var microphonePermission: VoicePermissionStateDto
  var recognizerAvailable: Bool
  var unavailableReason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VoiceCaptureCapabilitiesDto? {
    let contractVersion = pigeonVar_list[0] as! Int64
    let supported = pigeonVar_list[1] as! Bool
    let speechPermission = pigeonVar_list[2] as! VoicePermissionStateDto
    let microphonePermission = pigeonVar_list[3] as! VoicePermissionStateDto
    let recognizerAvailable = pigeonVar_list[4] as! Bool
    let unavailableReason: String? = nilOrValue(pigeonVar_list[5])

    return VoiceCaptureCapabilitiesDto(
      contractVersion: contractVersion,
      supported: supported,
      speechPermission: speechPermission,
      microphonePermission: microphonePermission,
      recognizerAvailable: recognizerAvailable,
      unavailableReason: unavailableReason
    )
  }
  func toList() -> [Any?] {
    return [
      contractVersion,
      supported,
      speechPermission,
      microphonePermission,
      recognizerAvailable,
      unavailableReason,
    ]
  }
  static func == (lhs: VoiceCaptureCapabilitiesDto, rhs: VoiceCaptureCapabilitiesDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VoiceCaptureApiPigeonInternal.deepEquals(lhs.contractVersion, rhs.contractVersion) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.supported, rhs.supported) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.speechPermission, rhs.speechPermission) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.microphonePermission, rhs.microphonePermission) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.recognizerAvailable, rhs.recognizerAvailable) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.unavailableReason, rhs.unavailableReason)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VoiceCaptureCapabilitiesDto")
    VoiceCaptureApiPigeonInternal.deepHash(value: contractVersion, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: supported, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: speechPermission, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: microphonePermission, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: recognizerAvailable, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: unavailableReason, hasher: &hasher)
  }

  public var description: String {
    return "VoiceCaptureCapabilitiesDto(contractVersion: \(String(describing: contractVersion)), supported: \(String(describing: supported)), speechPermission: \(String(describing: speechPermission)), microphonePermission: \(String(describing: microphonePermission)), recognizerAvailable: \(String(describing: recognizerAvailable)), unavailableReason: \(String(describing: unavailableReason)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VoiceCaptureStartRequestDto: Hashable, CustomStringConvertible {
  var contractVersion: Int64
  var operationId: String
  var mediaId: String
  var localeIdentifier: String
  var addsPunctuation: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VoiceCaptureStartRequestDto? {
    let contractVersion = pigeonVar_list[0] as! Int64
    let operationId = pigeonVar_list[1] as! String
    let mediaId = pigeonVar_list[2] as! String
    let localeIdentifier = pigeonVar_list[3] as! String
    let addsPunctuation = pigeonVar_list[4] as! Bool

    return VoiceCaptureStartRequestDto(
      contractVersion: contractVersion,
      operationId: operationId,
      mediaId: mediaId,
      localeIdentifier: localeIdentifier,
      addsPunctuation: addsPunctuation
    )
  }
  func toList() -> [Any?] {
    return [
      contractVersion,
      operationId,
      mediaId,
      localeIdentifier,
      addsPunctuation,
    ]
  }
  static func == (lhs: VoiceCaptureStartRequestDto, rhs: VoiceCaptureStartRequestDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VoiceCaptureApiPigeonInternal.deepEquals(lhs.contractVersion, rhs.contractVersion) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.mediaId, rhs.mediaId) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.localeIdentifier, rhs.localeIdentifier) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.addsPunctuation, rhs.addsPunctuation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VoiceCaptureStartRequestDto")
    VoiceCaptureApiPigeonInternal.deepHash(value: contractVersion, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: mediaId, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: localeIdentifier, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: addsPunctuation, hasher: &hasher)
  }

  public var description: String {
    return "VoiceCaptureStartRequestDto(contractVersion: \(String(describing: contractVersion)), operationId: \(String(describing: operationId)), mediaId: \(String(describing: mediaId)), localeIdentifier: \(String(describing: localeIdentifier)), addsPunctuation: \(String(describing: addsPunctuation)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VoiceCaptureAckDto: Hashable, CustomStringConvertible {
  var contractVersion: Int64
  var operationId: String
  var accepted: Bool
  var statusCode: VoiceCaptureStatusCodeDto
  var diagnosticMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VoiceCaptureAckDto? {
    let contractVersion = pigeonVar_list[0] as! Int64
    let operationId = pigeonVar_list[1] as! String
    let accepted = pigeonVar_list[2] as! Bool
    let statusCode = pigeonVar_list[3] as! VoiceCaptureStatusCodeDto
    let diagnosticMessage: String? = nilOrValue(pigeonVar_list[4])

    return VoiceCaptureAckDto(
      contractVersion: contractVersion,
      operationId: operationId,
      accepted: accepted,
      statusCode: statusCode,
      diagnosticMessage: diagnosticMessage
    )
  }
  func toList() -> [Any?] {
    return [
      contractVersion,
      operationId,
      accepted,
      statusCode,
      diagnosticMessage,
    ]
  }
  static func == (lhs: VoiceCaptureAckDto, rhs: VoiceCaptureAckDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VoiceCaptureApiPigeonInternal.deepEquals(lhs.contractVersion, rhs.contractVersion) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.accepted, rhs.accepted) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.statusCode, rhs.statusCode) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.diagnosticMessage, rhs.diagnosticMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VoiceCaptureAckDto")
    VoiceCaptureApiPigeonInternal.deepHash(value: contractVersion, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: accepted, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: statusCode, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: diagnosticMessage, hasher: &hasher)
  }

  public var description: String {
    return "VoiceCaptureAckDto(contractVersion: \(String(describing: contractVersion)), operationId: \(String(describing: operationId)), accepted: \(String(describing: accepted)), statusCode: \(String(describing: statusCode)), diagnosticMessage: \(String(describing: diagnosticMessage)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VoiceCaptureResultDto: Hashable, CustomStringConvertible {
  var contractVersion: Int64
  var operationId: String
  var resultId: String
  var temporaryFilePath: String
  var originDeviceId: String
  var createdAtMicros: Int64
  var durationMs: Int64
  var byteLength: Int64
  var mimeType: String
  var codec: String
  var sampleRateHz: Int64
  var channelCount: Int64
  var recognizedText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VoiceCaptureResultDto? {
    let contractVersion = pigeonVar_list[0] as! Int64
    let operationId = pigeonVar_list[1] as! String
    let resultId = pigeonVar_list[2] as! String
    let temporaryFilePath = pigeonVar_list[3] as! String
    let originDeviceId = pigeonVar_list[4] as! String
    let createdAtMicros = pigeonVar_list[5] as! Int64
    let durationMs = pigeonVar_list[6] as! Int64
    let byteLength = pigeonVar_list[7] as! Int64
    let mimeType = pigeonVar_list[8] as! String
    let codec = pigeonVar_list[9] as! String
    let sampleRateHz = pigeonVar_list[10] as! Int64
    let channelCount = pigeonVar_list[11] as! Int64
    let recognizedText: String? = nilOrValue(pigeonVar_list[12])

    return VoiceCaptureResultDto(
      contractVersion: contractVersion,
      operationId: operationId,
      resultId: resultId,
      temporaryFilePath: temporaryFilePath,
      originDeviceId: originDeviceId,
      createdAtMicros: createdAtMicros,
      durationMs: durationMs,
      byteLength: byteLength,
      mimeType: mimeType,
      codec: codec,
      sampleRateHz: sampleRateHz,
      channelCount: channelCount,
      recognizedText: recognizedText
    )
  }
  func toList() -> [Any?] {
    return [
      contractVersion,
      operationId,
      resultId,
      temporaryFilePath,
      originDeviceId,
      createdAtMicros,
      durationMs,
      byteLength,
      mimeType,
      codec,
      sampleRateHz,
      channelCount,
      recognizedText,
    ]
  }
  static func == (lhs: VoiceCaptureResultDto, rhs: VoiceCaptureResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VoiceCaptureApiPigeonInternal.deepEquals(lhs.contractVersion, rhs.contractVersion) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.resultId, rhs.resultId) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.temporaryFilePath, rhs.temporaryFilePath) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.originDeviceId, rhs.originDeviceId) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.createdAtMicros, rhs.createdAtMicros) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.byteLength, rhs.byteLength) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.mimeType, rhs.mimeType) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.codec, rhs.codec) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.sampleRateHz, rhs.sampleRateHz) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.channelCount, rhs.channelCount) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.recognizedText, rhs.recognizedText)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VoiceCaptureResultDto")
    VoiceCaptureApiPigeonInternal.deepHash(value: contractVersion, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: resultId, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: temporaryFilePath, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: originDeviceId, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: createdAtMicros, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: byteLength, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: mimeType, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: codec, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: sampleRateHz, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: channelCount, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: recognizedText, hasher: &hasher)
  }

  public var description: String {
    return "VoiceCaptureResultDto(contractVersion: \(String(describing: contractVersion)), operationId: \(String(describing: operationId)), resultId: \(String(describing: resultId)), temporaryFilePath: \(String(describing: temporaryFilePath)), originDeviceId: \(String(describing: originDeviceId)), createdAtMicros: \(String(describing: createdAtMicros)), durationMs: \(String(describing: durationMs)), byteLength: \(String(describing: byteLength)), mimeType: \(String(describing: mimeType)), codec: \(String(describing: codec)), sampleRateHz: \(String(describing: sampleRateHz)), channelCount: \(String(describing: channelCount)), recognizedText: \(String(describing: recognizedText)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VoiceCaptureEventDto: Hashable, CustomStringConvertible {
  var contractVersion: Int64
  var operationId: String
  var sequence: Int64
  var phase: VoiceCapturePhaseDto
  var statusCode: VoiceCaptureStatusCodeDto
  var diagnosticMessage: String? = nil
  var result: VoiceCaptureResultDto? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VoiceCaptureEventDto? {
    let contractVersion = pigeonVar_list[0] as! Int64
    let operationId = pigeonVar_list[1] as! String
    let sequence = pigeonVar_list[2] as! Int64
    let phase = pigeonVar_list[3] as! VoiceCapturePhaseDto
    let statusCode = pigeonVar_list[4] as! VoiceCaptureStatusCodeDto
    let diagnosticMessage: String? = nilOrValue(pigeonVar_list[5])
    let result: VoiceCaptureResultDto? = nilOrValue(pigeonVar_list[6])

    return VoiceCaptureEventDto(
      contractVersion: contractVersion,
      operationId: operationId,
      sequence: sequence,
      phase: phase,
      statusCode: statusCode,
      diagnosticMessage: diagnosticMessage,
      result: result
    )
  }
  func toList() -> [Any?] {
    return [
      contractVersion,
      operationId,
      sequence,
      phase,
      statusCode,
      diagnosticMessage,
      result,
    ]
  }
  static func == (lhs: VoiceCaptureEventDto, rhs: VoiceCaptureEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VoiceCaptureApiPigeonInternal.deepEquals(lhs.contractVersion, rhs.contractVersion) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.sequence, rhs.sequence) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.phase, rhs.phase) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.statusCode, rhs.statusCode) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.diagnosticMessage, rhs.diagnosticMessage) && VoiceCaptureApiPigeonInternal.deepEquals(lhs.result, rhs.result)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VoiceCaptureEventDto")
    VoiceCaptureApiPigeonInternal.deepHash(value: contractVersion, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: sequence, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: phase, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: statusCode, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: diagnosticMessage, hasher: &hasher)
    VoiceCaptureApiPigeonInternal.deepHash(value: result, hasher: &hasher)
  }

  public var description: String {
    return "VoiceCaptureEventDto(contractVersion: \(String(describing: contractVersion)), operationId: \(String(describing: operationId)), sequence: \(String(describing: sequence)), phase: \(String(describing: phase)), statusCode: \(String(describing: statusCode)), diagnosticMessage: \(String(describing: diagnosticMessage)), result: \(String(describing: result)))"
  }
}

private class VoiceCaptureApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VoiceCapturePhaseDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VoiceCaptureStatusCodeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VoicePermissionStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return VoiceCaptureCapabilitiesDto.fromList(self.readValue() as! [Any?])
    case 133:
      return VoiceCaptureStartRequestDto.fromList(self.readValue() as! [Any?])
    case 134:
      return VoiceCaptureAckDto.fromList(self.readValue() as! [Any?])
    case 135:
      return VoiceCaptureResultDto.fromList(self.readValue() as! [Any?])
    case 136:
      return VoiceCaptureEventDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VoiceCaptureApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VoiceCapturePhaseDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? VoiceCaptureStatusCodeDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? VoicePermissionStateDto {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? VoiceCaptureCapabilitiesDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? VoiceCaptureStartRequestDto {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? VoiceCaptureAckDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? VoiceCaptureResultDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? VoiceCaptureEventDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VoiceCaptureApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VoiceCaptureApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VoiceCaptureApiPigeonCodecWriter(data: data)
  }
}

class VoiceCaptureApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VoiceCaptureApiPigeonCodec(readerWriter: VoiceCaptureApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VoiceCaptureHostApi {
  func getCapabilities(localeIdentifier: String, completion: @escaping (Result<VoiceCaptureCapabilitiesDto, Error>) -> Void)
  func startCapture(request: VoiceCaptureStartRequestDto, completion: @escaping (Result<VoiceCaptureAckDto, Error>) -> Void)
  func stopCapture(operationId: String, completion: @escaping (Result<VoiceCaptureAckDto, Error>) -> Void)
  func cancelCapture(operationId: String, completion: @escaping (Result<VoiceCaptureAckDto, Error>) -> Void)
  func releaseResult(resultId: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VoiceCaptureHostApiSetup {
  static var codec: FlutterStandardMessageCodec { VoiceCaptureApiPigeonCodec.shared }
  /// Sets up an instance of `VoiceCaptureHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VoiceCaptureHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localeIdentifierArg = args[0] as! String
        api.getCapabilities(localeIdentifier: localeIdentifierArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let startCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.startCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VoiceCaptureStartRequestDto
        api.startCapture(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startCaptureChannel.setMessageHandler(nil)
    }
    let stopCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.stopCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let operationIdArg = args[0] as! String
        api.stopCapture(operationId: operationIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopCaptureChannel.setMessageHandler(nil)
    }
    let cancelCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.cancelCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let operationIdArg = args[0] as! String
        api.cancelCapture(operationId: operationIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelCaptureChannel.setMessageHandler(nil)
    }
    let releaseResultChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.interaction_foundation.VoiceCaptureHostApi.releaseResult\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseResultChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let resultIdArg = args[0] as! String
        api.releaseResult(resultId: resultIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseResultChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VoiceCaptureFlutterApiProtocol {
  func onCaptureEvent(event eventArg: VoiceCaptureEventDto, completion: @escaping (Result<Void, VoiceCapturePigeonError>) -> Void)
}
class VoiceCaptureFlutterApi: VoiceCaptureFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: VoiceCaptureApiPigeonCodec {
    return VoiceCaptureApiPigeonCodec.shared
  }
  func onCaptureEvent(event eventArg: VoiceCaptureEventDto, completion: @escaping (Result<Void, VoiceCapturePigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.interaction_foundation.VoiceCaptureFlutterApi.onCaptureEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(VoiceCapturePigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
